version: '3'
services:

  nginx:
    image: nginx:1.13.7
    depends_on:
      - flask
    ports:
      - 5555:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
        - application

  flask:
    build: 
      context: ./server/
      dockerfile: Dockerfile
    hostname: flask
    depends_on:
      - mongo
    environment: 
      - MONGO_HOST=mongo
      - API_KEY=${API_KEY}
      - env=production
    env_file:
      - ./.env
    command: gunicorn -b 0.0.0.0:8000 -w 2 main:manager
    restart: unless-stopped
    networks:
      - application

  mongo:
    image: mongo:3.4.22
    restart: unless-stopped
    volumes:
      - dbdata:/data/db
    networks:
      - application

  svelte:
        build:
            context: ./frontend/
            dockerfile: Dockerfile
        environment:
            - API_URL=flask
            - API_KEY=${API_KEY}
        env_file:
          - ./.env
        command: node ./__sapper__/build
        restart: unless-stopped
        ports:
          - 80:3000
        networks:
          - application


volumes:
  dbdata:

networks:
  application:
